version: '3'

# TODO: make users/groups for shared data
# TODO: put data in a shared directory

services:
  web:
    image: szwtest
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - /home/kwebb/swat-zero-waste-v2:/var/www/szw
    user: 8001:8001
    env_file:
      - production.env
    restart: unless-stopped
  db:
    image: postgres:12
    volumes:
      - /data/szwdb:/var/lib/postgresql/data
    user: 8000:8000
    env_file:
      - production.env
    restart: unless-stopped
